# Generated by Django 5.1.4 on 2024-12-23 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_is_temporary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_user_firebas_b8ee51_idx',
            old_name='users_user_firebas_idx',
        ),
    ]
